import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { trpc } from '../utils/trpc'

export default function Home() {
  const utils = trpc.useContext();
  let page = trpc.hello.useQuery();
  
  if(!page.data) {
    return <p>Loading...</p>
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {JSON.stringify(page.data)}
      </main>
    </div>
  )
}
